export {
  getSupabaseBrowserClient,
  getOrCreateUser,
  getActiveHunts,
  getUserHunts,
  getUserClaims,
  subscribeToNewHunts,
  subscribeToNotifications,
  getAllQuests,
  getDisputes,
  getVerifierStats,
  getLeaderboard,
  getCommunityActivities,
  getBrandProfile,
  getHuntById,
  applyAsVerifier,
  registerBrand,
  subscribeToCommunityActivities,
} from "./client";
export type { Database } from "./types";
