[package]
name = "hunt-factory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk.workspace = true

[features]
factory-integration = []
full-integration = ["factory-integration"]

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
